### ISSUE TITLE
Server error na opleggen kaart vlak na vuile Frits tijd

### ISSUE THREAD

**Issue by fpk47** [FritsGamer/Fritsen#33]
`> node server.js

App listening on Port 9999
/Users/s4d/Fritsen/server.js:224
		nextPlayer(m);
		           ^

ReferenceError: m is not defined
    at Timeout._onTimeout (/Users/s4d/Fritsen/server.js:224:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Fritsen@0.1.9 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Fritsen@0.1.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/s4d/.npm/_logs/2020-04-29T09_48_24_494Z-debug.log`

**Comment by fpk47** [comment]
@wjvaandrager dit wordt veroorzaakt door jou laatste commit

Reconnect fix with setTimeout
https://github.com/FritsGamer/Fritsen/commit/5c41aa949ed95ab953cee647abf13adfb8bbafaa
